/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.2.0. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module InstructionRAM
    (
      input [31:0] FETCH_ADDRESS

    , output reg [31:0] DATA
    );

  // blockRamFile begin
  reg [31:0] RAM [0:512-1];

  initial begin
    $readmemb("instructions.bin",RAM);
  end

  always @(FETCH_ADDRESS) begin : InstructionRAM_blockRamFile
      DATA <= RAM[FETCH_ADDRESS];
  end

endmodule

