/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.2.0. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module InstructionRAM
    (
      input [31:0] Fetch_Addr

    , output reg [31:0] Instruction
    );

  // blockRamFile begin
  reg  [31:0] RAM [0:512-1];

  
  initial begin
    $readmemb("instructions.bin",RAM);
  end

  always @(Fetch_Addr) begin : InstructionRAM_blockRamFile
      Instruction <= RAM[Fetch_Addr >> 2];
  end

endmodule

